name: fastrm

services:
    irods-catalog:
        build:
            context: irods_catalog
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        depends_on:
            - irods-catalog

    redis:
        image: redis

    celery:
        build:
            context: celery
        depends_on:
            - redis

    # TODO: Consider using new python HTTP API wrapper
    #irods-client-http-api:
        #image: irods/irods_http_api:0.3.0
        #volumes:
            #- ./irods_client_http_api/config.json:/config.json:ro
        #ports:
            #- "9001:9000"
        #restart: on-failure
        #depends_on:
            #irods-catalog-provider:
                #condition: service_healthy
